addons:
  ssh_known_hosts:
    - git.savannah.nongnu.org
    - github.com

language: go

go:
  - 1.14.x

os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y ninja; fi

script:
  - service/build.bat
  - cd service
  - ziti-ci publish artifactory --groupId amd64.windows --artifactId ziti-tunnel-win --version 0.0.1 --target ziti-tunnel.exe

before_script:
  - go get github.com/netfoundry/ziti-ci@v1.2