addons:
  ssh_known_hosts:
    - git.savannah.nongnu.org
    - github.com

import:
  - source: netfoundry/ziti-ci:ziti-ci.yml@may22-updates

language: go

go:
  - 1.14.x

os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y zip ninja; fi

script:
  - service/build.bat
  - service/publish.bat