addons:
  ssh_known_hosts:
    - git.savannah.nongnu.org
    - github.com

import:
  - source: netfoundry/ziti-ci:ziti-ci.yml@v1.2

language: go

go:
  - 1.14.x

os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y ninja; fi

script:
  - service/build.bat
  - cd service
  - ziti-ci publish artifactory --groupId ziti-tunnel-win.amd64.windows --artifactId ziti-tunnel-win --version 0.0.2-SNAPSHOT --target ziti-tunnel.zip
