if: (type = push AND branch IN (master, dev)) OR (type = pull_request)

language: go

go:
  - 1.14.x

os:
  - windows

# first try at only building PR or branch push - updated to the first if on line 1 above
branches:
  except:
  - installer

#  only:
#    - "master"

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y zip ninja --no-progress; fi

before_script:
  - export GIT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

script:
  - powershell -file update-versions.ps1
  - service/publish.bat
