addons:
  ssh_known_hosts:
    - git.savannah.nongnu.org
    - github.com

import:
  - source: githunetfoundry/ziti-ci:ziti-ci.yml@may22

language: go

go:
  - 1.14.x

os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y zip ninja; fi

script:
  - service/build.bat
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; ziti-ci publish artifactory --groupId=ziti-tunnel-win.amd64.windows --artifactId=ziti-tunnel-win --version=0.0.3 --target=service/ziti-tunnel-win.zip
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; ziti-ci publish artifactory --groupId=ziti-tunnel-win.amd64.windows --artifactId=ziti-tunnel-win --version=0.0.3-SNAPSHOT --target=service/ziti-tunnel-win.zip
