import:
  - source: netfoundry/ziti-ci:ziti-ci.yml@v1

language: go
os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y ninja; fi

script:
  - service/build.bat
  