import:
  - source: netfoundry/ziti-ci:ziti-ci.yml@v1

language: go
os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y ninja; fi

script:
  - echo 1 > version
  - ziti-ci configure-git
  - pwd
  - cd service
  - pwd
  - dir
  - .\build-step1.bat
  - build.bat
  