language: go

go:
  - 1.14.x

os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y zip ninja openssh; fi

before_script:
  - export GIT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

script:
  - cmon_travis.bat


