name: Build Installer

on:
  push:
    branches: 
      - installer
      - '*issue-130*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}

defaults:
  run:
    working-directory: ${env:GITHUB_WORKSPACE}
    
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Hello world
        run: echo Hello world $GITHUB_WORKSPACE