name: Build Installer

on:
  push:
    branches: 
      - installer
      - '*issue-130*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}
  CURDIR: ${{github.workspace}}

jobs:
  one:
    runs-on: windows-latest
    env:
      FIRST_NAME: Mona
      CURDIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@master
      - uses: NuGet/setup-nuget@v1.0.2
      - uses: microsoft/setup-msbuild@v1
      - name: Trying to run choco install
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: Install advanced installer
        run: choco install advanced-installer --yes
      - name: Restore nuget packages
        run: nuget restore ZitiDesktopEdge.sln
      - name: Build UI and Assemble Installer
        run: powershell -File .\Installer\build.ps1
