name: Build Installer

on:
  push:
    branches: 
      - installer
      - '*issue-130*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}
  CURDIR: ${{github.workspace}}

jobs:
  one:
    runs-on: windows-latest
    env:
      FIRST_NAME: Mona
      CURDIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@master
      - uses: NuGet/setup-nuget@v1.0.2
      - uses: microsoft/setup-msbuild@v1
      - name: Restore nuget packages
        run: nuget restore ZitiDesktopEdge.sln
      - name: Build UI and Assemble Installer
        run: powershell -File .\Installer\build.ps1
