name: Build Installer

on:
  push:
    branches: 
      - installer
      - '*issue-130*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}
  CURDIR: ${{github.workspace}}

jobs:
  one:
    name: New Name
    runs-on: windows-latest
    env:
      CURDIR: ${{ github.workspace }}
      CODE: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
      SOME_KEY: ${{ secrets.SOME_KEY }}
    steps:
      - shell: pwsh
        env:
          SUPER_SECRET: ${{ secrets.SOME_KEY }}
        run: |
          echo "$env:SUPER_SECRET" 
      - name: Print new build number
        run: |
          echo "Build number is ${{ steps.buildnumber.outputs.build_number }}"
          echo "Build number is ${env:BUILD_NUMBER}"
        env:
          BUILD_NUMBER: "Please Work"

      - run: |
          echo "${env:CODE} - ${env:SOME_KEY}"
          echo "${env:SOME_KEY}" > some_file.txt
          type some_file.txt
        env:
          CURDIR: ${{ github.workspace }}
#      - uses: actions/checkout@master
#      - uses: NuGet/setup-nuget@v1.0.2
#      - uses: microsoft/setup-msbuild@v1
#      - name: Trying to run choco install.
#        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
#      - name: Install advanced installer
#       run: choco install advanced-installer wixtoolset --yes
#      - name: Restore nuget packages
#        run: nuget restore ZitiDesktopEdge.sln
#      - name: Write key file
#        env:
#          AUTH: ${{ secrets.AUTH }}
#        run: |
#          echo "$AUTH" | base64 --decode > ${HOME}/../WinSign.p12
#
#      - name: Build UI and Assemble Installer
#        run: powershell -File .\Installer\build.ps1
