name: Build Installer

on:
  push:
    branches: 
      - installer
      - '*issue-130*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}
  CURDIR: ${{github.workspace}}

jobs:
  one:
    runs-on: windows-latest
    env:
      CURDIR: ${{ github.workspace }}
    steps:
      - run: echo "%CURDIR% - $CURDIR %SOME_KEY% - $SOME_KEY"
        env:
          CURDIR: ${{ github.workspace }}
          SOME_KEY: ${{ secrets.SOME_KEY }}
#      - uses: actions/checkout@master
#      - uses: NuGet/setup-nuget@v1.0.2
#      - uses: microsoft/setup-msbuild@v1
#      - name: Trying to run choco install.
#        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
#      - name: Install advanced installer
#       run: choco install advanced-installer wixtoolset --yes
#      - name: Restore nuget packages
#        run: nuget restore ZitiDesktopEdge.sln
#      - name: Write key file
#        env:
#          AUTH: ${{ secrets.AUTH }}
#        run: |
#          echo "$AUTH" | base64 --decode > ${HOME}/../WinSign.p12
#
#      - name: Build UI and Assemble Installer
#        run: powershell -File .\Installer\build.ps1
