name: Build Installer

on:
  push:
    branches: 
      - installer
      - '*issue-130*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}

jobs:
  Build:
    runs-on: windows-latest
    env:
      working-direcotry: ${env:GITHUB_WORKSPACE}
    steps:
      - uses: actions/checkout@v2    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2
      - name: Build UI and Assemble Installer
        run: powershell -File .\Installer\build.ps1
        working-direcotry: ${env:GITHUB_WORKSPACE}
        