name: CI

on:
  push:
    branches: 
      - dev
    tags:
      - "v*-beta.*"
      - "v*-rc.*"
  pull_request:
    branches: 
      - "release*"

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2

    - name: Build
      shell: cmd
      run: ./service/publish.bat